/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.LibroControlador;
import Modelo.Libro;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duoc
 */
public class BuscarLibro extends javax.swing.JFrame {

    /**
     * Creates new form BuscarDocumento
     */
    
    LibroControlador libroControlador = new LibroControlador();
            
    public BuscarLibro() {
        initComponents();
    }
    
    public void buscarUnLibro(int codigo)
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
        modelo.getDataVector().removeAllElements();//limpia la jtable
        Libro unLibro;
        try {
            unLibro = libroControlador.buscarLibro(codigo);
      
        Object filaDatos[] = new Object[6];
        filaDatos[0]=unLibro.getCodigo();
        filaDatos[1]=unLibro.getAnioPublicacion();
        filaDatos[2]=unLibro.getTitulo();
        filaDatos[3]=unLibro.getAutor();
        filaDatos[4]=unLibro.getEditorial();
        filaDatos[5]=unLibro.isPrestado();
        modelo.addRow(filaDatos);
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }
    
    public void crearTabla()
    {
        
        DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
        modelo.getDataVector().removeAllElements();//limpia la jtable
        try {
            
            
            ArrayList<Libro> lista = libroControlador.buscarTodoLibro();
            
            Object filaDatos[] = new Object[6];
            
            for(int i=0; i<lista.size(); i++)
            {
                  filaDatos[0]= lista.get(i).getCodigo();
                  filaDatos[1]= lista.get(i).getAnioPublicacion();
                  filaDatos[2] = lista.get(i).getTitulo();
                  filaDatos[3] = lista.get(i).getAutor();
                  filaDatos[4] = lista.get(i).getEditorial();
                  filaDatos[5] = lista.get(i).isPrestado();
                  modelo.addRow(filaDatos);
            
            }
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
          
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        caja_codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_buscarTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));

        jLabel5.setText("Codigo:");

        bt_buscarTodos.setText("Buscar");
        bt_buscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(caja_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(bt_buscarTodos)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(caja_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscarTodos))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Buscar");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Año Publicacion", "Titulo", "Autor", "Editorial", "Prestado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaLibros);

        btModificar.setText("Modificar");
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btModificar)
                        .addGap(28, 28, 28)
                        .addComponent(btEliminar)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModificar)
                    .addComponent(btEliminar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarTodosActionPerformed
        // TODO add your handling code here:
        if(caja_codigo.getText()!=" ")
     
        {
            crearTabla();
            
            
        }
        else{
            buscarUnLibro(Integer.parseInt(caja_codigo.getText()));
                }  
    }//GEN-LAST:event_bt_buscarTodosActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        if(tablaLibros.getRowCount()>0)  //rowcount muestra las filsa que hay
        {
            int fila=tablaLibros.getSelectedRow();//retorna el numero de la fila seleccionada
            if(fila >+-1)
            {
                DefaultTableModel modelo= (DefaultTableModel) tablaLibros.getModel();
                int codigo=Integer.parseInt (modelo.getValueAt(fila, 0).toString());
                if(codigo>0)
                {
                    int anio=Integer.parseInt (modelo.getValueAt(fila, 1).toString());
                    String titulo=(modelo.getValueAt(fila, 2).toString());
                    String autor=(modelo.getValueAt(fila, 3).toString());
                    String editorial=(modelo.getValueAt(fila, 4).toString());
                    boolean prestado = Boolean.parseBoolean(modelo.getValueAt(fila, 5).toString());
                    try {
                        String mensaje = libroControlador.modificarLibro(prestado, codigo, anio, titulo, autor, editorial);
                     JOptionPane.showMessageDialog(this, mensaje);
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Seleccione una fila");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "tabla sin datos");
        }
    }//GEN-LAST:event_btModificarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed

        if (tablaLibros.getRowCount() > 0) //rowcount muestra las filsa que hay
        {
            int fila = tablaLibros.getSelectedRow();//retorna el numero de la fila seleccionada
            if (fila > +-1) {
                DefaultTableModel modelo = (DefaultTableModel) tablaLibros.getModel();
                int codigo = Integer.parseInt(modelo.getValueAt(fila, 0).toString());
                if (codigo > 0) 
                {
                    String mensaje= libroControlador.eliminar(codigo);
                    JOptionPane.showMessageDialog(this, "Eliminacion exitosa");
                    crearTabla();
                            
                }

            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }

    }//GEN-LAST:event_btEliminarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton bt_buscarTodos;
    private javax.swing.JTextField caja_codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    // End of variables declaration//GEN-END:variables
}
